@startuml
'https://plantuml.com/sequence-diagram

title Charger labyrinthe
activate MoteurJeu
MoteurJeu -> Utilisateur : demande charger fichier
activate Utilisateur
Utilisateur --> MoteurJeu : fichier 
deactivate Utilisateur

MoteurJeu -> ModeleLabyrinthe : createLabyrinthe()
activate ModeleLabyrinthe


@enduml